LINUXFOLDER = '/home/alan/linux-4.16'
ARCH = 'x86'
QEMU = 'qemu-system-x86_64'
MEMORYSIZE = '512M'
INITRDADDR = LINUXFOLDER + '/initrd.img'
ASMFILE = '/home/alan/linux-4.16/vmlinux.txt'
PRUNED = True
PRUNELEVEL = 1
PRUNEOUTCOME = 0